### ISSUE TITLE
你好能不能更新一下op，我想添加一些外挂网卡，因为不是最新版，op官方现在没有patch进去现在有些插件无法安装

### ISSUE THREAD

**Issue by DroidMAX-Tang** [thank243/Hiwifi-HC5611-ROM#1]

**Comment by thank243** [comment]
I have PR this patch to openwrt offical. If you are not in a hurry, you can wait for the official update.

**Comment by thank243** [comment]
@DroidMAX-Tang The openwrt official have merged the device. So you can build it via openwrt repo.
